services:
  ingestion-service:
    image: "eternalbliss/ingestion-service:latest"
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - DHAN_CLIENT_ID=${DHAN_CLIENT_ID}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - INGESTION_CRON=${INGESTION_CRON}
      - DHAN_INFLIGHT_LIMIT=${DHAN_INFLIGHT_LIMIT}
    restart: unless-stopped
