services:
  ingestion-service:
    image: "eternalbliss/ingestion-service:0.1"
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - INGESTION_CRON=${INGESTION_CRON}
    restart: unless-stopped
